#define PATH_PROGNAME "@PROGNAME@"

#define PATH_VERSION "@EMACS_VERSION@"

#ifdef EXEC_PREFIX_USER_DEFINED
#define PATH_EXEC_PREFIX "@XEMACS_EXEC_PREFIX@"
#endif

#ifdef PREFIX_USER_DEFINED
#define PATH_PREFIX "@XEMACS_PREFIX@"
#endif

#ifdef LISPDIR_USER_DEFINED
#define  PATH_LOADSEARCH "@XEMACS_LISPDIR@"
#endif

#ifdef MODULEDIR_USER_DEFINED
#define  PATH_MODULESEARCH "@XEMACS_MODULEDIR@"
#endif

#ifdef SITELISPDIR_USER_DEFINED
#define  PATH_SITE "@XEMACS_SITELISPDIR@"
#endif

#ifdef SITEMODULEDIR_USER_DEFINED
#define  PATH_SITE_MODULES "@XEMACS_SITEMODULEDIR@"
#endif

#ifdef EARLY_PACKAGE_DIRECTORIES_USER_DEFINED
#define PATH_EARLY_PACKAGE_DIRECTORIES "@EARLY_PACKAGE_DIRECTORIES@"
#endif

#ifdef LATE_PACKAGE_DIRECTORIES_USER_DEFINED
#define PATH_LATE_PACKAGE_DIRECTORIES "@XEMACS_LATE_PACKAGES@"
#endif

#ifdef LAST_PACKAGE_DIRECTORIES_USER_DEFINED
#define PATH_LAST_PACKAGE_DIRECTORIES "@LAST_PACKAGE_DIRECTORIES@"
#endif

#ifdef PACKAGE_PATH_USER_DEFINED
#define PATH_PACKAGEPATH "@PACKAGE_PATH@"
#endif

#ifdef ARCHLIBDIR_USER_DEFINED
#define PATH_EXEC "@XEMACS_ARCHLIBDIR@"
#endif

#ifdef ETCDIR_USER_DEFINED
#define PATH_DATA "@XEMACS_ETCDIR@"
#endif

#ifdef DOCDIR_USER_DEFINED
#define PATH_DOC "@XEMACS_DOCDIR@"
#endif

#ifdef INFODIR_USER_DEFINED
#define PATH_INFO "@XEMACS_INFODIR@"
#endif

#ifdef INFOPATH_USER_DEFINED
#define PATH_INFOPATH "@INFOPATH@"
#endif
