if(XEMACS_WITH_CANNA)
  check_include_file("canna/ccommon.h" HAVE_CANNA_CCOMMON_H)
  if(HAVE_CANNA_CCOMMON_H)
    check_library_exists("canna" "RkInitialize" "" HAVE_LIBCANNA)
    if(HAVE_LIBCANNA)
      set(HAVE_CANNA ON)
      set(CANNA_LIBRARIES "canna")
    endif()
  else()
    check_include_file("ccommon.h" HAVE_CCOMMON_H)
    if(HAVE_CCOMMON_H)
      check_library_exists("canna" "RkInitialize" "" HAVE_LIBCANNA2)
      if(HAVE_LIBCANNA2)
        set(HAVE_CANNA ON)
        set(CANNA_LIBRARIES "canna")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_WNN)
  check_include_file("wnn/wnnlib.h" HAVE_WNN_WNNLIB_H)
  if(HAVE_WNN_WNNLIB_H)
    check_library_exists("wnn" "jd_string_to_romaji" "" HAVE_LIBWNN)
    if(HAVE_LIBWNN)
      set(HAVE_WNN ON)
      set(WNN_LIBRARIES "wnn")
    endif()
  else()
    check_include_file("wnnlib.h" HAVE_WNNLIB_H)
    if(HAVE_WNNLIB_H)
      check_library_exists("wnn" "jd_string_to_romaji" "" HAVE_LIBWNN2)
      if(HAVE_LIBWNN2)
        set(HAVE_WNN ON)
        set(WNN_LIBRARIES "wnn")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_WNN6)
  check_include_file("wnn6/wnnlib.h" HAVE_WNN6_WNNLIB_H)
  if(HAVE_WNN6_WNNLIB_H)
    check_library_exists("wnn6" "jd_string_to_romaji" "" HAVE_LIBWNN6)
    if(HAVE_LIBWNN6)
      set(HAVE_WNN6 ON)
      set(WNN6_LIBRARIES "wnn6")
    endif()
  endif()
endif()

if(XEMACS_WITH_XIM)
  if(HAVE_X_WINDOWS)
    check_include_file("X11/Xlib.h" HAVE_X11_XLIB_H)
    if(HAVE_X11_XLIB_H)
      check_c_source_compiles("
        #include <X11/Xlib.h>
        #include <X11/Xlocale.h>
        int main(void) {
          XIM xim;
          XOpenIM(NULL, NULL, NULL, NULL);
          return 0;
        }
      " HAVE_XIM)
      if(HAVE_XIM)
        set(HAVE_X_WINDOWS_XIM ON)
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_SOUND)
  if(HAVE_ALSA OR HAVE_OSS)
    set(HAVE_SOUND ON)
  endif()
endif()

if(XEMACS_WITH_MODULES)
  if(HAVE_DLFCN_H)
    check_function_exists("dlopen" HAVE_DLOPEN)
    if(HAVE_DLOPEN)
      set(HAVE_MODULES ON)
    endif()
  endif()
endif()

if(XEMACS_WITH_BIGNUM)
  find_package(GMP)
  if(GMP_FOUND)
    set(HAVE_GMP ON)
    set(HAVE_LIBGMP ON)
    include_directories(${GMP_INCLUDE_DIR})
  else()
    check_include_file("gmp.h" HAVE_GMP_H)
    if(HAVE_GMP_H)
      check_library_exists("gmp" "mpz_init" "" HAVE_LIBGMP2)
      if(HAVE_LIBGMP2)
        set(HAVE_GMP ON)
        set(HAVE_LIBGMP ON)
        set(GMP_LIBRARIES "gmp")
      endif()
    endif()
  endif()
  
  if(NOT HAVE_GMP)
    find_package(OpenSSL)
    if(OPENSSL_FOUND)
      set(HAVE_OPENSSL ON)
      set(HAVE_BIGNUM ON)
      include_directories(${OPENSSL_INCLUDE_DIR})
    endif()
  endif()
endif()

if(XEMACS_WITH_TLS)
  find_package(OpenSSL)
  if(OPENSSL_FOUND)
    set(HAVE_SSL ON)
    set(HAVE_TLS ON)
    include_directories(${OPENSSL_INCLUDE_DIR})
  else()
    check_include_file("openssl/ssl.h" HAVE_OPENSSL_SSL_H)
    if(HAVE_OPENSSL_SSL_H)
      check_library_exists("ssl" "SSL_library_init" "" HAVE_LIBSSL)
      check_library_exists("crypto" "BIO_new" "" HAVE_LIBCRYPTO)
      if(HAVE_LIBSSL AND HAVE_LIBCRYPTO)
        set(HAVE_SSL ON)
        set(HAVE_TLS ON)
        set(OPENSSL_LIBRARIES "ssl" "crypto")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_SOCKS)
  check_include_file("socks.h" HAVE_SOCKS_H)
  if(HAVE_SOCKS_H)
    check_library_exists("socks" "SOCKSinit" "" HAVE_LIBSOCKS)
    if(HAVE_LIBSOCKS)
      set(HAVE_SOCKS ON)
      set(SOCKS_LIBRARIES "socks")
    endif()
  endif()
endif()

if(XEMACS_WITH_GNOME)
  if(HAVE_GTK)
    find_package(gnome)
    if(gnome_FOUND)
      set(HAVE_GNOME ON)
    endif()
  endif()
endif()

if(XEMACS_WITH_FONTCONFIG)
  find_package(Fontconfig)
  if(Fontconfig_FOUND)
    set(HAVE_FONTCONFIG ON)
    include_directories(${Fontconfig_INCLUDE_DIR})
  else()
    check_include_file("fontconfig/fontconfig.h" HAVE_FONTCONFIG_FONTCONFIG_H)
    if(HAVE_FONTCONFIG_FONTCONFIG_H)
      check_library_exists("fontconfig" "FcInit" "" HAVE_LIBFONTCONFIG)
      if(HAVE_LIBFONTCONFIG)
        set(HAVE_FONTCONFIG ON)
        set(Fontconfig_LIBRARIES "fontconfig")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_XFACE)
  check_include_file("compface.h" HAVE_COMPFACE_H)
  if(HAVE_COMPFACE_H)
    check_library_exists("compface" "uncompface" "" HAVE_LIBCOMPFACE)
    if(HAVE_LIBCOMPFACE)
      set(HAVE_XFACE ON)
      set(COMPFACE_LIBRARIES "compface")
    endif()
  endif()
endif()

if(XEMACS_WITH_TOOLTALK)
  check_include_file("tt_c.h" HAVE_TT_C_H)
  if(HAVE_TT_C_H)
    check_library_exists("tt" "tt_open" "" HAVE_LIBTT)
    if(HAVE_LIBTT)
      set(HAVE_TOOLTALK ON)
      set(TOOLTALK_LIBRARIES "tt")
    endif()
  endif()
endif()

if(XEMACS_WITH_DNET)
  check_include_file("netdnet/dnet.h" HAVE_NETDNET_DNET_H)
  if(HAVE_NETDNET_DNET_H)
    check_library_exists("dnet" "dnet_conn" "" HAVE_LIBDNET)
    if(HAVE_LIBDNET)
      set(HAVE_DNET ON)
      set(DNET_LIBRARIES "dnet")
    endif()
  else()
    check_include_file("sys/dnet.h" HAVE_SYS_DNET_H)
    if(HAVE_SYS_DNET_H)
      check_library_exists("dnet" "dnet_conn" "" HAVE_LIBDNET2)
      if(HAVE_LIBDNET2)
        set(HAVE_DNET ON)
        set(DNET_LIBRARIES "dnet")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_TTY)
  if(HAVE_NCURSES)
    set(HAVE_TTY ON)
  else()
    set(HAVE_TTY ON)
    message(STATUS "TTY support enabled but no termcap library found")
  endif()
else()
  set(HAVE_TTY OFF)
endif()

if(XEMACS_WITH_CLASH_DETECTION)
  set(HAVE_CLASH_DETECTION ON)
endif()

if(XEMACS_WITH_DRAGNDROP)
  if(HAVE_X_WINDOWS)
    set(HAVE_DRAGNDROP ON)
  endif()
endif()

if(XEMACS_WITH_CDE)
  if(HAVE_X_WINDOWS)
    check_include_file("Dt/Dt.h" HAVE_DT_DT_H)
    if(HAVE_DT_DT_H)
      check_library_exists("Dt" "DtInitialize" "" HAVE_LIBDT)
      if(HAVE_LIBDT)
        set(HAVE_CDE ON)
        set(CDE_LIBRARIES "Dt")
      endif()
    endif()
  endif()
endif()

if(XEMACS_WITH_EXTERNAL_WIDGET)
  if(HAVE_X_WINDOWS)
    set(HAVE_EXTERNAL_WIDGET ON)
  endif()
endif()

if(XEMACS_WITH_MENUBARS)
  set(HAVE_MENUBARS ON)
endif()

if(XEMACS_WITH_SCROLLBARS)
  set(HAVE_SCROLLBARS ON)
endif()

if(XEMACS_WITH_DIALOGS)
  set(HAVE_DIALOGS ON)
endif()

if(XEMACS_WITH_WIDGETS)
  set(HAVE_WIDGETS ON)
endif()

if(XEMACS_WITH_TOOLBARS)
  set(HAVE_TOOLBARS ON)
endif()

if(XEMACS_WITH_XFT)
  if(HAVE_X_WINDOWS AND HAVE_XRENDER AND HAVE_FONTCONFIG)
    set(HAVE_XFT ON)
  endif()
endif()

if(XEMACS_WITH_MEMORY_USAGE_STATS)
  set(HAVE_MEMORY_USAGE_STATS ON)
endif()

if(XEMACS_WITH_ERROR_CHECKING)
  set(ERROR_CHECK_TYPES ON)
  add_definitions(-DERROR_CHECK_TYPES=1)
endif()

if(XEMACS_WITH_ASSERTIONS)
  set(EMACS_ASSERT ON)
  add_definitions(-DEMACS_ASSERT=1)
endif()

if(XEMACS_WITH_DEBUG)
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(DEBUG_XEMACS ON)
    add_definitions(-DDEBUG_XEMACS=1)
  endif()
endif()

if(XEMACS_WITH_QUICK_BUILD)
  set(QUICK_BUILD ON)
endif()

if(XEMACS_WITH_DUMP_IN_EXEC)
  set(EMACS_DUMP_IN_EXEC ON)
else()
  set(EMACS_DUMP_IN_EXEC OFF)
endif()

if(XEMACS_WITH_REL_ALLOC)
  set(HAVE_REL_ALLOC ON)
endif()

if(XEMACS_MAIL_LOCKING)
  if(XEMACS_MAIL_LOCKING STREQUAL "lockf")
    set(HAVE_MAIL_LOCKF ON)
  elseif(XEMACS_MAIL_LOCKING STREQUAL "flock")
    set(HAVE_MAIL_FLOCK ON)
  elseif(XEMACS_MAIL_LOCKING STREQUAL "file")
    set(HAVE_MAIL_LOCKFILE ON)
  elseif(XEMACS_MAIL_LOCKING STREQUAL "locking")
    set(HAVE_MAIL_LOCKING ON)
  elseif(XEMACS_MAIL_LOCKING STREQUAL "mmdf")
    set(HAVE_MAIL_MMDF_ON)
  elseif(XEMACS_MAIL_LOCKING STREQUAL "pop")
    set(HAVE_MAIL_POP_ON)
  endif()
endif()

if(HAVE_GNOME)
  set(HAVE_GNOME_DIALOGS ON)
endif()

if(HAVE_WIDGETS)
  if(XEMACS_WITH_WIDGETS_TYPE STREQUAL "lucid")
    set(HAVE_LUCID_WIDGETS ON)
    if(HAVE_MENUBARS)
      set(HAVE_LUCID_MENUBARS ON)
    endif()
    if(HAVE_SCROLLBARS)
      set(HAVE_LUCID_SCROLLBARS ON)
    endif()
    if(HAVE_DIALOGS)
      set(HAVE_LUCID_DIALOGS ON)
    endif()
  elseif(XEMACS_WITH_WIDGETS_TYPE STREQUAL "motif")
    set(HAVE_MOTIF_WIDGETS ON)
    if(HAVE_MENUBARS)
      set(HAVE_MOTIF_MENUBARS ON)
    endif()
    if(HAVE_SCROLLBARS)
      set(HAVE_MOTIF_SCROLLBARS ON)
    endif()
    if(HAVE_DIALOGS)
      set(HAVE_MOTIF_DIALOGS ON)
    endif()
  elseif(XEMACS_WITH_WIDGETS_TYPE STREQUAL "athena")
    set(HAVE_ATHENA_WIDGETS ON)
    if(HAVE_MENUBARS)
      set(HAVE_ATHENA_MENUBARS ON)
    endif()
    if(HAVE_SCROLLBARS)
      set(HAVE_ATHENA_SCROLLBARS ON)
    endif()
    if(HAVE_DIALOGS)
      set(HAVE_ATHENA_DIALOGS ON)
    endif()
  elseif(XEMACS_WITH_WIDGETS_TYPE STREQUAL "gtk")
    if(HAVE_GTK)
      set(HAVE_GTK_WIDGETS ON)
      if(HAVE_MENUBARS)
        set(HAVE_GTK_MENUBARS ON)
      endif()
      if(HAVE_SCROLLBARS)
        set(HAVE_GTK_SCROLLBARS ON)
      endif()
      if(HAVE_DIALOGS)
        set(HAVE_GTK_DIALOGS ON)
      endif()
    endif()
  elseif(XEMACS_WITH_WIDGETS_TYPE STREQUAL "msw")
    if(XEMACS_OPSYS MATCHES "windows|mingw|cygwin")
      set(HAVE_MSW_WIDGETS ON)
      if(HAVE_MENUBARS)
        set(HAVE_MSW_MENUBARS ON)
      endif()
      if(HAVE_SCROLLBARS)
        set(HAVE_MSW_SCROLLBARS ON)
      endif()
      if(HAVE_DIALOGS)
        set(HAVE_MSW_DIALOGS ON)
      endif()
    endif()
  endif()
endif()

if(HAVE_X_WINDOWS)
  set(HAVE_X11 ON)
  if(HAVE_MENUBARS AND NOT (HAVE_LUCID_MENUBARS OR HAVE_MOTIF_MENUBARS OR HAVE_ATHENA_MENUBARS OR HAVE_GTK_MENUBARS OR HAVE_MSW_MENUBARS))
    if(HAVE_GTK)
      set(HAVE_GTK_MENUBARS ON)
      set(HAVE_GTK_WIDGETS ON)
    else()
      set(HAVE_LUCID_MENUBARS ON)
      set(HAVE_LUCID_WIDGETS ON)
    endif()
  endif()
  if(HAVE_SCROLLBARS AND NOT (HAVE_LUCID_SCROLLBARS OR HAVE_MOTIF_SCROLLBARS OR HAVE_ATHENA_SCROLLBARS OR HAVE_GTK_SCROLLBARS OR HAVE_MSW_SCROLLBARS))
    if(HAVE_GTK)
      set(HAVE_GTK_SCROLLBARS ON)
      set(HAVE_GTK_WIDGETS ON)
    else()
      set(HAVE_LUCID_SCROLLBARS ON)
      set(HAVE_LUCID_WIDGETS ON)
    endif()
  endif()
  if(HAVE_DIALOGS AND NOT (HAVE_LUCID_DIALOGS OR HAVE_MOTIF_DIALOGS OR HAVE_ATHENA_DIALOGS OR HAVE_GTK_DIALOGS OR HAVE_GNOME_DIALOGS OR HAVE_MSW_DIALOGS))
    if(HAVE_GTK)
      set(HAVE_GTK_DIALOGS ON)
      set(HAVE_GTK_WIDGETS ON)
    else()
      set(HAVE_LUCID_DIALOGS ON)
      set(HAVE_LUCID_WIDGETS ON)
    endif()
  endif()
endif()

if(XEMACS_WITH_SITE_LISP)
  set(HAVE_SITE_LISP ON)
endif()

if(XEMACS_WITH_SITE_MODULES)
  set(HAVE_SITE_MODULES ON)
endif()

if(HAVE_WMM_ALLOC)
  set(HAVE_WMM_ALLOC ON)
endif()

if(XEMACS_WITH_MSW)
  if(XEMACS_OPSYS MATCHES "windows|mingw|cygwin")
    set(HAVE_MS_WINDOWS ON)
    if(HAVE_MENUBARS)
      set(HAVE_MSW_MENUBARS ON)
    endif()
    if(HAVE_SCROLLBARS)
      set(HAVE_MSW_SCROLLBARS ON)
    endif()
    if(HAVE_DIALOGS)
      set(HAVE_MSW_DIALOGS ON)
    endif()
  endif()
endif()

if(HAVE_X_WINDOWS AND HAVE_X11_SM)
  set(HAVE_X11_SM ON)
  set(HAVE_SESSION ON)
endif()

if(HAVE_WMCOMMAND)
  set(HAVE_WMCOMMAND ON)
endif()

if(HAVE_XFS)
  set(HAVE_XFS ON)
endif()

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "Build type" FORCE)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  add_definitions(-DDEBUG)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -O0")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -DNDEBUG")
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O2 -g -DNDEBUG")
elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Os -DNDEBUG")
endif()

if(USE_GCC)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
  
  if(CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL 4.0)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wextra")
  endif()
  
  if(CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL 3.0)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-sign-compare -Wno-comment")
  endif()
endif()

if(XEMACS_CONFIG_OPSYSFILE)
  string(REGEX REPLACE "^s/([^/]+)\\.h$" "\\1" OPSYS_NAME "${XEMACS_CONFIG_OPSYSFILE}")
  set(OPSYS_NAME "${OPSYS_NAME}")
else()
  set(OPSYS_NAME "${XEMACS_OPSYS}")
endif()

if(XEMACS_CONFIG_MACHFILE)
  string(REGEX REPLACE "^m/([^/]+)\\.h$" "\\1" MACHINE_NAME "${XEMACS_CONFIG_MACHFILE}")
  set(MACHINE_NAME "${MACHINE_NAME}")
else()
  set(MACHINE_NAME "${XEMACS_MACHINE}")
endif()

message(STATUS "System: ${MACHINE_NAME}-${OPSYS_NAME}")
