string(TOLOWER "${CMAKE_SYSTEM_NAME}" XEMACS_OPSYS_LOWER)
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" XEMACS_MACHINE_LOWER)

set(XEMACS_OPSYS "${XEMACS_OPSYS_LOWER}")
set(XEMACS_MACHINE "${XEMACS_MACHINE_LOWER}")

set(XEMACS_CONFIG_OPSYSFILE "")
set(XEMACS_CONFIG_MACHFILE "")

message(STATUS "Detecting system: ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}")

if(XEMACS_OPSYS_LOWER MATCHES "linux")
  set(XEMACS_OPSYS "linux")
  set(XEMACS_CONFIG_OPSYSFILE "s/linux.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "darwin")
  set(XEMACS_OPSYS "darwin")
  set(XEMACS_CONFIG_OPSYSFILE "s/darwin.h")
  add_definitions(-DUSE_PARAM_H)
elseif(XEMACS_OPSYS_LOWER MATCHES "freebsd")
  set(XEMACS_OPSYS "freebsd")
  set(XEMACS_CONFIG_OPSYSFILE "s/freebsd.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "netbsd")
  set(XEMACS_OPSYS "netbsd")
  set(XEMACS_CONFIG_OPSYSFILE "s/netbsd.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "openbsd")
  set(XEMACS_OPSYS "openbsd")
  set(XEMACS_CONFIG_OPSYSFILE "s/openbsd.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "sunos|solaris")
  set(XEMACS_OPSYS "sol2")
  set(XEMACS_CONFIG_OPSYSFILE "s/sol2.h")
  add_definitions(-D__EXTENSIONS__)
elseif(XEMACS_OPSYS_LOWER MATCHES "aix")
  set(XEMACS_OPSYS "aix4-2")
  set(XEMACS_CONFIG_OPSYSFILE "s/aix4-2.h")
  if(NOT DEFINED CMAKE_C_COMPILER_ID OR CMAKE_C_COMPILER_ID STREQUAL "XL")
    set(NON_GNU_CC "xlc")
  endif()
elseif(XEMACS_OPSYS_LOWER MATCHES "hp-ux|hpux")
  set(XEMACS_OPSYS "hpux11")
  set(XEMACS_CONFIG_OPSYSFILE "s/hpux11.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "irix")
  set(XEMACS_OPSYS "irix6-5")
  set(XEMACS_CONFIG_OPSYSFILE "s/irix6-5.h")
elseif(XEMACS_OPSYS_LOWER MATCHES "windows")
  if(MINGW)
    set(XEMACS_OPSYS "mingw32")
  elseif(CYGWIN)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(XEMACS_OPSYS "cygwin64")
    else()
      set(XEMACS_OPSYS "cygwin32")
    endif()
  else()
    set(XEMACS_OPSYS "windowsnt")
    set(XEMACS_CONFIG_OPSYSFILE "s/windowsnt.h")
  endif()
elseif(XEMACS_OPSYS_LOWER MATCHES "gnu")
  set(XEMACS_OPSYS "gnu")
else()
  message(STATUS "Unknown OS: ${XEMACS_OPSYS_LOWER}, using generic detection")
endif()

if(XEMACS_MACHINE_LOWER MATCHES "sparc")
  set(XEMACS_MACHINE "sparc")
  set(XEMACS_CONFIG_MACHFILE "m/sparc.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "alpha")
  set(XEMACS_MACHINE "alpha")
  set(XEMACS_CONFIG_MACHFILE "m/alpha.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "mips")
  set(XEMACS_MACHINE "mips")
  set(XEMACS_CONFIG_MACHFILE "m/mips.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "powerpc|ppc")
  set(XEMACS_MACHINE "powerpc")
  set(XEMACS_CONFIG_MACHFILE "m/powerpc.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "hppa|parisc")
  set(XEMACS_MACHINE "hp800")
  set(XEMACS_CONFIG_MACHFILE "m/hp800.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "arm")
  set(XEMACS_MACHINE "arm")
  set(XEMACS_CONFIG_MACHFILE "m/arm.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "i[3-9]86|x86")
  set(XEMACS_MACHINE "intel386")
  set(XEMACS_CONFIG_MACHFILE "m/intel386.h")
elseif(XEMACS_MACHINE_LOWER MATCHES "x86_64|amd64")
  set(XEMACS_MACHINE "x86_64")
  set(XEMACS_CONFIG_MACHFILE "m/x86_64.h")
else()
  message(STATUS "Unknown machine: ${XEMACS_MACHINE_LOWER}")
endif()

if(XEMACS_CONFIG_OPSYSFILE)
  message(STATUS "Operating system file: ${XEMACS_CONFIG_OPSYSFILE}")
else()
  message(STATUS "No specific operating system file - using configure-time autodetection only")
endif()

if(XEMACS_CONFIG_MACHFILE)
  message(STATUS "Machine file: ${XEMACS_CONFIG_MACHFILE}")
else()
  message(STATUS "No specific machine file - using configure-time autodetection only")
endif()

set(config_opsysfile "${XEMACS_CONFIG_OPSYSFILE}")
set(config_machfile "${XEMACS_CONFIG_MACHFILE}")

if(NOT DEFINED XEMACS_WITH_DYNAMIC)
  if(XEMACS_OPSYS MATCHES "hpux")
    set(XEMACS_WITH_DYNAMIC OFF)
  else()
    set(XEMACS_WITH_DYNAMIC ON)
  endif()
endif()

if(APPLE)
  set(CMAKE_FIND_FRAMEWORK "LAST")
endif()

if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID STREQUAL "GNU")
  set(USE_GCC ON)
  add_definitions(-DUSE_GCC=1)
  
  if(CMAKE_C_COMPILER MATCHES "g\\+\\+")
    set(USE_GPLUSPLUS ON)
    add_definitions(-DUSE_GPLUSPLUS=1)
  endif()
  
  set(XEMACS_GCC_VERSION "${CMAKE_C_COMPILER_VERSION}")
  message(STATUS "GCC version: ${XEMACS_GCC_VERSION}")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
  message(STATUS "Using Clang compiler")
elseif(CMAKE_C_COMPILER_ID STREQUAL "Intel")
  set(__ICC ON)
  add_definitions(-D__ICC=1)
  message(STATUS "Using Intel C++ compiler")
elseif(CMAKE_C_COMPILER_ID MATCHES "SunPro|SunPro_C")
  set(__SUNPRO_C ON)
  add_definitions(-D__SUNPRO_C=1)
  message(STATUS "Using SunPro compiler")
elseif(CMAKE_C_COMPILER_ID MATCHES "XL|VisualAge")
  set(__DECC ON)
  add_definitions(-D__DECC=1)
  message(STATUS "Using DEC C compiler")
endif()

if(XEMACS_OPSYS MATCHES "linux")
  include(CheckIncludeFile)
  check_include_file("features.h" HAVE_FEATURES_H)
  if(HAVE_FEATURES_H)
    check_c_source_compiles("
      #include <features.h>
      #if !defined(__GLIBC__) && !defined(__GNU_LIBRARY__)
      #error Not a GNU libc system
      #endif
      int main(void) { return 0; }
    " HAVE_GLIBC)
    if(HAVE_GLIBC)
      add_definitions(-DHAVE_GLIBC=1)
      add_definitions(-D_GNU_SOURCE=1)
      message(STATUS "Detected GNU libc")
    endif()
  endif()
endif()

check_c_source_runs("
  int main(void) {
  #if defined(__STDC_VERSION__) && (__STDC_VERSION__ - 0) >= 199901L
    return 0;
  #else
    return 1;
  #endif
  }
" HAVE_C99)

if(XEMACS_OPSYS MATCHES "sol2|solaris")
  add_definitions(-D__EXTENSIONS__=1)
  
  execute_process(COMMAND uname -r
    OUTPUT_VARIABLE OS_RELEASE_RAW
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  
  if(OS_RELEASE_RAW MATCHES "([0-9]+)\\.([0-9]+)")
    set(OS_RELEASE_MAJOR "${CMAKE_MATCH_1}")
    set(OS_RELEASE_MINOR "${CMAKE_MATCH_2}")
    if(OS_RELEASE_MINOR MATCHES "^[0-9]$")
      set(OS_RELEASE_MINOR "0${OS_RELEASE_MINOR}")
    endif()
    set(OS_RELEASE "${OS_RELEASE_MAJOR}${OS_RELEASE_MINOR}")
    add_definitions(-DOS_RELEASE=${OS_RELEASE})
  endif()
  
  if(HAVE_C99)
    add_definitions(-D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=200112L)
  else()
    add_definitions(-D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=199506L)
  endif()
elseif(XEMACS_OPSYS MATCHES "linux")
  if(HAVE_C99)
    add_definitions(-D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=200112L)
  else()
    add_definitions(-D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=199506L)
  endif()
elseif(XEMACS_OPSYS MATCHES "freebsd")
  message(STATUS "FreeBSD detected - not defining _XOPEN_SOURCE to avoid restricting symbols")
endif()

if(CMAKE_SYSTEM_NAME MATCHES "AIX")
  add_definitions(-D_ALL_SOURCE=1)
endif()
